### ISSUE TITLE
Links on Installation point to french version

### ISSUE THREAD

**Issue by groso** [TYPO3-Documentation/TYPO3CMS-Tutorial-Templating#21]
Both links pointing to the Getting Started Tut contain a parameter to chose the french version.

<a class="reference external" href="https://docs.typo3.org/typo3cms/GettingStartedTutorial/Localization/fr_FR/Index.html#start" title="(in Getting Started Tutorial v7.6)"><span class="xref std std-ref">Getting Started Tutorial</span></a>

**Comment by Chrissitopher** [comment]
This is the source code, which is creating the two links: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Templating/blob/latest/Documentation/Installation/Index.rst. Actually, the code looks correct to me.

Also the `intersphinx_mapping` from https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Templating/blob/latest/Documentation/Settings.cfg looks good.

@marble: Do you know, why these links have a /fr/ in them anyway?

**Comment by sypets** [comment]
I think this should be fixed now, see also https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Editors/issues/5

If there is still a problem, please reopen or create a new issue. Thanks!
