### ISSUE TITLE
Update documentation to fluid based templates

### ISSUE THREAD

**Issue by fawmi** [TYPO3-Documentation/TYPO3CMS-Tutorial-Templating#24]
I believe this (TYPO3CMS-Tutorial-Templating) is the most important documentation for TYPO3 beginners, but all the guides are pretty much outdated.
The guides are about old "markers" and "subparts" templating system.
I believe this documentation needs a rewrite.

https://docs.typo3.org/typo3cms/TemplatingTutorial/Tasks/WorkingHTML/HtmlTemplate/Index.html

**Comment by sypets** [comment]
A new tutorial was introduced by now: https://docs.typo3.org/typo3cms/SitePackageTutorial/

The tutorial you are referring to has been updated for the "latest" branch. 

So I think this issue can be closed now.
