### ISSUE TITLE
Provide good and secure Fluid examples

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/TYPO3CMS-Tutorial-Templating#39]
## Misleading, insecure content

https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Templating/blame/10.4/Documentation/BasicFluidTemplates/Index.rst#L167

* using `f:format.htmlEntitiesDecode` on user-submitted content, that has been encoded already (`styles.content.get`) is potentially insecure
* in this case it probably might be better using `f:format.raw` (take data as-is, given it has been encoded for HTML before - otherwise again security implications)
* see https://typo3.org/security/advisory/typo3-ext-sa-2021-007 as a reference (it's not 100% the same here, but similar)

## Provide good examples on how to use Fluid

* mention all contexts and use-cases
  + regular "scalar" values
  + nested content rendering (like above, double encoded content)
  + special handling, e.g. "(only) allow line-break & transform to HTML" in values
  + special handling, e.g. "(only) allow `<i>`, `<b>`" in values
* explain scenarios
* provide good (complete) examples - show input data, show output data

## Fluid Toolbox

* `<f:format.raw>`
* `<f:format:html [parseFuncTSPath="..."]>`
* `<f:format.htmlSpecialChars [doubleEncode="true"]>`
* `<f:format.htmlEntitiesDecode>`
* plain `{variable}`

**Comment by ohader** [comment]
see https://github.com/benjaminkott/bootstrap_package/issues/996 as well

**Comment by linawolf** [comment]
The tutorial was archived
